{% set name = "thrift_sasl" %}
{% set version = "0.3.0" %}
{% set hash = "80e015290e7c9afc5b4864bfb964e841d4d98e1d70f74bc216cf269f243f3362" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ hash }}

build:
  number: 1001
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
  run:
    - python
    - thrift >=0.10
    - pure-sasl  # [win]
    - sasl  # [not win]

test:
  imports:
    - thrift_sasl

about:
  home: https://github.com/cloudera/thrift_sasl
  license: Apache 2.0
  summary: Thrift SASL module that implements TSaslClientTransport
  license_family: Apache
  dev_url: https://github.com/cloudera/thrift_sasl
  doc_url: https://github.com/cloudera/thrift_sasl
  # https://github.com/cloudera/thrift_sasl/pull/7
  # license_file: LICENSE

extra:
  recipe-maintainers:
    - mariusvniekerk
    - ericdill
    - wesm
